########################################################################################################################
# Repo tool base settings
########################################################################################################################

[repo]

[repo_build.build]
"platform:windows-x86_64".enabled = true

[repo_build.msbuild]
vs_version = "vs2022"
link_host_toolchain = true

# Use the Kit Template repo configuration as a base. Only override things specific to the repo.
import_configs = [
    "${root}/_repo/deps/repo_kit_tools/kit-template/repo.toml",
    "${root}/_repo/deps/repo_kit_tools/kit-template/repo-external-app.toml",
]

# Repository Name
name = "kit-diffusion-painter"


########################################################################################################################
# Extensions precacher
########################################################################################################################

[repo_precache_exts]
# Apps to run and precache
apps = [
    "${root}/source/apps/texture_painter_app.kit",
]

registries = [
    { name = "kit/default", url = "https://ovextensionsprod.blob.core.windows.net/exts/kit/prod/shared" },
    { name = "kit/sdk", url = "https://ovextensionsprod.blob.core.windows.net/exts/kit/prod/sdk/${kit_version_short}/${kit_git_hash}" },
]

