[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "AI Texture Painter"
description = "Turn any image into a texture paint brush with AI and paint on the surface of 3D meshes."
# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = "https://github.com/NVIDIA-Omniverse/kit-extension-template"

# One of categories for UI.
category = "Other"

# Keywords for the extension
keywords = ["AI", "diffusion", "texture", "paint", "brush", "3D", "mesh"]

# Icon to show in the extension manager
icon = "data/icon.png"

# Preview to show in the extension manager
preview_image = "data/preview.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.ui" = {}
"omni.kit.window.extensions" = {}
"omni.pip.kaolin" = {tag="0_15_0_t2_0_1"}
"omni.paint.system.core" = {}

[[test]]
dependencies = [
    "omni.kit.material.library"
]
stdoutFailPatterns.exclude = [
    "*Failed to parse version * of one of the dependencies ('omni.usd.schema.physx')*",
    "*[omni.kit.app._impl] [py stderr]:*",
    "*Could not register * for any Viewport backend*",
    "*IRendererImpl::updateGpuResourcesForTexture CUDA error*"
]

# Main python module this extension provides, it will be publicly available as "import omni.hello.world".
[[python.module]]
name = "aitoybox.texture_painter"

[[python.module]]
path = "pip_prebundle"

[python.pipapi]
# List of additional directories with pip achives to be passed into pip using ``--find-links`` arg.
# Relative paths are relative to extension root. Tokens can be used.
archiveDirs = []

# Commands passed to pip install before extension gets enabled. Can also contain flags, like `--upgrade`, `--no--index`, etc.
# Refer to: https://pip.pypa.io/en/stable/reference/requirements-file-format/
requirements = []

# Allow going to online index if package can't be found locally (not recommended)
use_online_index = true

# Use this to specify a list of additional repositories if your pip package is hosted somewhere other
# than the default repo(s) configured in pip. Will pass these to pip with "--extra-index-url" argument
repositories = []

[settings]
exts."aitoybox.texture_painter".gpu_id = 0
exts."aitoybox.texture_painter".texture_painter_url = "ws://localhost:6060/websocket/"
